MyPortfolio/Controllers/AdminLoginController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyPortfolio.DAL.Context;
using MyPortfolio.DAL.Entities;
using MyPortfolio.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MyPortfolio.Controllers
{
	public class AdminLoginController : Controller
	{
		private readonly MyPortfolioContext _context;
		private readonly UserManager<AppUser> _userManager;
		private readonly RoleManager<AppRole> _roleManager;
		private readonly SignInManager<AppUser> _signInManager;

		public AdminLoginController(MyPortfolioContext context, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager, RoleManager<AppRole> roleManager)
		{
			_context = context;
			_signInManager = signInManager;
			_userManager = userManager;
			_roleManager = roleManager;
		}

		public IActionResult Index()
		{
			return View();
		}

        [HttpPost]
        public async Task<IActionResult> Index(UserLoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.UserName, model.Password, false, true);

                if (result.Succeeded)
                {
                    var userId = _userManager.Users.Where(x => x.UserName == model.UserName).Select(y => y.Id).FirstOrDefault();
                    var userRoleId = _context.UserRoles.Where(x => x.UserId.Equals(userId)).Select(y => y.RoleId).FirstOrDefault();
                    var adminRoleId = _roleManager.Roles.Where(x => x.Name.Equals("Admin") || x.Name.Equals("admin")).Select(y => y.Id).FirstOrDefault();

                    if (userRoleId == adminRoleId)
                    {
                        return RedirectToAction("Index", "Statistic");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Kullanıcı Admin rolüne sahip değil.");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Kullanıcı adı veya şifre yanlış.");
                }
            }

            // Return the model with validation errors if any
            return View(model);
        }



        public async Task<IActionResult> LogOut()
		{
			await _signInManager.SignOutAsync();
			return RedirectToAction("Index", "Default");
		}
	}
}

MyPortfolio/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyPortfolio.Controllers

    
{
    public class DefaultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MyPortfolio/Controllers/MessageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyPortfolio.DAL.Context;
using MyPortfolio.DAL.Entities;
using System.Linq;

namespace MyPortfolio.Controllers
{
	[Authorize(Roles = "Admin")]
	public class MessageController : Controller
    {
        private readonly MyPortfolioContext _context;

        public MessageController(MyPortfolioContext context)
        {
            _context = context;
        }

        // Gelen mesajları listelemek için
        public IActionResult Inbox()
        {
            var values = _context.Messages.ToList();
            return View(values);
        }

        public IActionResult ChangeIsReadToTrue(int id) // Mesaji okundu olarak isaretlemek icin
        {
            var value = _context.Messages.Find(id);
            value.IsRead = true;
            _context.SaveChanges();
            return RedirectToAction("Inbox");
        }

        public IActionResult ChangeIsReadToFalse(int id) // Mesaji okunmadi olarak isaretlemek icin
        {
            var value = _context.Messages.Find(id);
            value.IsRead = false;
            _context.SaveChanges();
            return RedirectToAction("Inbox");
        }

        public IActionResult DeleteMessage(int id)
        {
            var value = _context.Messages.Find(id);
            _context.Messages.Remove(value);
            _context.SaveChanges();
            return RedirectToAction("Inbox");
        }
        public IActionResult MessageDetail(int id)
        {
            var value = _context.Messages.Find(id);
            value.IsRead = true;
            _context.SaveChanges();
            return View(value);
        }
		[HttpGet]
		public IActionResult SendMessage()
		{
			return View("~/Views/Shared/Components/_ContactComponentPartial/Default.cshtml");
		}
		[HttpPost]
		public IActionResult SendMessage(Message message) // Ana sayfadan gelen mesajlarin gonderimi
		{
			if (ModelState.IsValid)
			{
				message.SendDate = DateTime.Now;
				message.IsRead = false;
				_context.Messages.Add(message);
				_context.SaveChanges();
				return Json(new { success = true });
			}
			return Json(new { success = false });
		}

	}
}

MyPortfolio/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyPortfolio.DAL.Entities;
using MyPortfolio.Helpers.Images;
using System.Security.Claims;
using System;
using MyPortfolio.DAL.Context;
using Microsoft.EntityFrameworkCore;
using MyPortfolio.Models;
using MyPortfolio.DAL.Extensions;

namespace MyPortfolio.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProfileController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ClaimsPrincipal _user;
        private readonly MyPortfolioContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly IImageHelper _imageHelper;
        public ProfileController(IHttpContextAccessor httpContextAccessor, MyPortfolioContext context, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, IImageHelper imageHelper)
        {
            _httpContextAccessor = httpContextAccessor;
            _context = context;
            _user = httpContextAccessor.HttpContext.User;
            _userManager = userManager;
            _signInManager = signInManager;
            _imageHelper = imageHelper;
        }
        [HttpGet]
        public IActionResult Update()
        {
            var userId = _user.GetLoggedInUserId(); // Giris yapan kisinin id'si
            var user = _context.Users.Include(i => i.Image).Where(x => x.Id == userId).FirstOrDefault(); // Giren kisinin id'sine ait bilgileri image'i include ederek getir.
            UserProfileViewModel viewModel = new()
            {
                Name = user.Name,
                Surname = user.Surname,
                Email = user.Email,
                UserName = user.UserName,
                PhoneNumber = user.PhoneNumber,
                ImageId = user.ImageId,
            };
            if (user.ImageId is not null)
                ViewBag.UserImage = user.Image.FileName;
            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Update(UserProfileViewModel viewModel)
        {
            var userId = _user.GetLoggedInUserId(); // Giris yapan kisinin id'si
            var user = await _userManager.FindByIdAsync(userId.ToString());
            Guid? imageId = user.ImageId; // Giris yapan kullanicinin image id'si
            var isVerified = await _userManager.CheckPasswordAsync(user, viewModel.CurrentPassword); // Mevcuttaki sifre dogruysa true donecek.
            if (isVerified && viewModel.NewPassword != null) // Eger yeni sifre alanina deger girilmisse sifre degistirme islemi yapilacak.
            {
                var result = await _userManager.ChangePasswordAsync(user, viewModel.CurrentPassword, viewModel.NewPassword); // Sifre degisme islemi
                if (result.Succeeded)
                {
                    await _userManager.UpdateSecurityStampAsync(user);
                    await _signInManager.SignOutAsync(); // Sifre degistirildigi icin cikis yaptirdik.
                    await _signInManager.PasswordSignInAsync(user, viewModel.NewPassword, true, false); // Ardindan yeni sifreyle otomatikman tekrar giris yaptiriyoruz.
                    user.Name = viewModel.Name;
                    user.Surname = viewModel.Surname;
                    user.Email = viewModel.Email;
                    user.UserName = viewModel.UserName;
                    user.PhoneNumber = viewModel.PhoneNumber;
                    user.ImageId = imageId;
                    if (viewModel.Photo != null) // Eger kullanici resim sectiyse resim yukleme isleminin ardindan ImageId bilgisi guncelleniyor.
                    {
                        // Resim yukleme islemleri
                        var imageUpload = await _imageHelper.Upload(viewModel.Name, viewModel.Photo);
                        Image image = new(imageUpload.FullName, viewModel.Photo.ContentType);
                        await _context.Images.AddAsync(image);
                        user.ImageId = image.Id;
                    }
                    await _userManager.UpdateAsync(user);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "Statistic");
                }
                else
                    return View();
            }
            else if (isVerified)
            {
                await _userManager.UpdateSecurityStampAsync(user);
                user.Name = viewModel.Name;
                user.Surname = viewModel.Surname;
                user.Email = viewModel.Email;
                user.UserName = viewModel.UserName;
                user.PhoneNumber = viewModel.PhoneNumber;
                user.ImageId = imageId;
                if (viewModel.Photo != null) // Eger kullanici resim sectiyse resim yukleme isleminin ardindan ImageId bilgisi guncelleniyor.
                {
                    // Resim yukleme islemleri
                    var imageUpload = await _imageHelper.Upload(viewModel.Name, viewModel.Photo);
                    Image image = new(imageUpload.FullName, viewModel.Photo.ContentType);
                    await _context.Images.AddAsync(image);
                    user.ImageId = image.Id;
                }
                await _userManager.UpdateAsync(user);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Statistic");
            }
            else
                return View();
        }
    }
}

MyPortfolio/Views/Shared/Components/_LayoutNavbarComponentPartial/Default.cshtml
@model List<ToDoList>
<div class="main-header">
    <div class="logo-header">
        <a href="#" class="logo">
            Admin Paneli
        </a>
        <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <button class="topbar-toggler more"><i class="la la-ellipsis-v"></i></button>
    </div>
    <nav class="navbar navbar-header navbar-expand-lg">
        <div class="container-fluid">
            <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
               
                @await Component.InvokeAsync("UnreadMessageList")
                <li class="nav-item dropdown hidden-caret">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="la la-bell"></i>
                        @if (ViewBag.toDoListCount != 0)
                        {
                            <span class="notification">@ViewBag.toDoListCount</span>
                        }
                    </a>
                    <ul class="dropdown-menu notif-box" aria-labelledby="navbarDropdown">
                        <li>
                            @if (ViewBag.toDoListCount != 0)
                            {
                                <div class="dropdown-title">@ViewBag.toDoListCount Yeni Hatırlatıcınız Var</div>
                            }
                            else
                            {
                                <div class="dropdown-title">Henüz Yeni Bir Hatırlatıcınız Yok</div>
                            }
                        </li>
                        <li>
                            <div class="notif-center">
                                @foreach(var item in Model ){
                                    <a href="#">
                                        <div class="notif-icon notif-success"> <i class="@item.ImageUrl"></i> </div>
                                        <div class="notif-content">
                                            <span class="block">
                                                @item.Title
                                            </span>
                                            <span class="time">@item.Date.ToShortDateString()</span>
                                        </div>
                                    </a>
                                }
                               
                       
                            </div>
                        </li>
                        <li>
                            <a class="see-all" href="javascript:void(0);"> <strong>Tüm bildirimleri göster</strong> <i class="la la-angle-right"></i> </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false"> <img src="~/Ready-Bootstrap-Dashboard-master/assets/img/ben.jpg" alt="user-img" width="36" class="img-circle"><span>Kübra Yalçın</span></span> </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <div class="user-box">
                                <div class="u-img">
                                    @if (ViewBag.userImageId is not null)
                                    {
                                        <img src="~/images/@ViewBag.UserImage" alt="user">
                                    }
                                    else
                                    {
                                        <img src="~/icons/user-avatar-profile.png" alt="user">
                                    }
                                </div>
                                <div class="u-text">
                                    <h4>@ViewBag.UserName</h4>
                                    <p class="text-muted">@ViewBag.UserMail</p><a asp-controller="Profile" asp-action="Update" class="btn btn-rounded btn-danger btn-sm">Profili Gör</a>
                                </div>
                            </div>
                        </li>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Profile" asp-action="Update"><i class="ti-user"></i> Profilim</a>
                        <a class="dropdown-item" asp-controller="Default" asp-action="Index"></i> Siteye Git</a>
                        <a class="dropdown-item" asp-controller="Message" asp-action="Inbox"><i class="ti-email"></i> Gelen Mesajlar</a>
                        <a class="dropdown-item" asp-controller="AdminLogin" asp-action="LogOut"><i class="fa fa-power-off"></i> Çıkış Yap</a>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
            </ul>
        </div>
    </nav>
</div>