MyPortfolio/Controllers/FeatureController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Microsoft.EntityFrameworkCore;
using MyPortfolio.DAL.Context;
using MyPortfolio.DAL.Entities;
using MyPortfolio.Helpers.Images;
using MyPortfolio.Models;
using System;

namespace MyPortfolio.Controllers
{
	[Authorize(Roles = "Admin")]
	public class FeatureController : Controller
    {
        private readonly MyPortfolioContext _context;
        private readonly IImageHelper _imageHelper;

        public FeatureController(MyPortfolioContext context, IImageHelper imageHelper)
        {
            _imageHelper = imageHelper;
            _context = context;
        }
        public IActionResult Index()
        {
            // Ana sayfada one cikan alan yazisi icin
            var feature = _context.Features.Include(i => i.Image).FirstOrDefault();
            ViewBag.featureId = feature.FeatureId;
            return View(feature);
        }
        [HttpGet]
        public IActionResult Update(int featureId)
        {
            // Feature tablosu ile Image tablosunu birbirine include ediyoruz (Feature tablosunu listelerken ilgili kayida ait resmi cekebilmek icin)
            var value = _context.Features.Include(i => i.Image).Where(x => x.FeatureId == featureId).FirstOrDefault();
            ViewBag.imageFileName = value.Image.FileName;

            FeatureUpdateViewModel viewModel = new FeatureUpdateViewModel()
            {
                FeatureId = value.FeatureId,
                Title = value.Title,
                Description = value.Description,
                ImageId = value.ImageId,
            };

            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Update(FeatureUpdateViewModel viewModel)
        {
            var feature = _context.Features.Include(i => i.Image).Where(x => x.FeatureId == viewModel.FeatureId).FirstOrDefault();

            if (viewModel.Photo != null) // Eger bir resim secilmisse
            {
                if (viewModel.ImageId != null) // Eger feature guncelleme sirasında ImageId bos degilse yani bir resim varsa o resmi silecegiz.
                    _imageHelper.Delete(feature.Image.FileName); // Once feature'de var olan resmi silecek

                // Ardindan yeni bir image yukleme islemi
                var imageUpload = await _imageHelper.Upload(viewModel.Title, viewModel.Photo);
                Image image = new(imageUpload.FullName, viewModel.Photo.ContentType);
                await _context.Images.AddAsync(image);
                await _context.SaveChangesAsync();

                feature.ImageId = image.Id;
            }

            feature.Title = viewModel.Title;
            feature.Description = viewModel.Description;

            _context.Features.Update(feature);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

MyPortfolio/Views/Feature/Index.cshtml
@model Feature
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div class="content" style="margin-bottom:20em;">
    <div class="container-fluid">
        <h4 class="page-title">Öne Çıkan Alan</h4>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Öne Çıkan Yazı</div>
                    </div>
                    <div class="card-body">
                        <div class="card-sub">
                            Öne Çıkan Yazı ile ilgili işlemleri aşağıdaki panelden yapabilirsiniz.
                        </div>
                        <table class="table mt-3">
                            <thead>
                                <tr>
                                    <th scope="col">Başlık</th>
                                    <th scope="col">Açıklama</th>
                                    @if (Model.ImageId is not null)
                                    {
                                        <th scope="col">Görsel</th>
                                    }
                                    <th scope="col">Güncelle</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>@Model.Title</td>
                                    <td>@Model.Description</td>
                                    @if (Model.ImageId is not null)
                                    {
                                        <td><img src="~/images/@Model.Image.FileName" style="width:10em; height:7em;" /></td>
                                    }
                                    <td><a data-id="@ViewBag.featureId" asp-controller="Feature" asp-action="Update" asp-route-featureId="@ViewBag.featureId" class="btn btn-success">Güncelle</a></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MyPortfolio/Views/Feature/Update.cshtml
@model FeatureUpdateViewModel
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div class="content" style="margin-bottom:20em;">
    <div class="container-fluid">
        <h4 class="page-title">Öne Çıkan Alan</h4>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Öne Çıkan Yazı Güncelleme Sayfası</div>
                    </div>
                    <div class="card-body">
                        <form asp-controller="Feature" asp-action="Update" method="post" enctype="multipart/form-data">
                            <input type="hidden" asp-for="FeatureId" />
                            <label>Başlık</label>
                            <input type="text" asp-for="Title" class="form-control" />
                            <br />
                            <label>Açıklama</label>
                            <textarea rows="4" class="form-control" asp-for="Description"></textarea>
                            <br />
                            <div class="row">
                                <div class="col-md-5">
                                    <label>Öne Çıkan Alan İçin Görsel</label>
                                    <input type="file" asp-for="Photo" accept="image/*" class="form-control" />
                                    <br />
                                </div>
                                <div class="col-md-7">
                                    @if (Model.ImageId is not null)
                                    {
                                        <label>Mevcut Görsel</label>
                                        <br />
                                        <img src="~/images/@ViewBag.imageFileName" style="width:20em; height:12em;" />
                                        <br />
                                    }
                                </div>
                            </div>
                            <button class="btn btn-success">Güncelle</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>